/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author lucas
 */
public class aswad extends javax.swing.JPanel {

    /**
     * Creates new form visualizarProdutos
     */
    public aswad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        painelTop = new javax.swing.JPanel();
        tituloPage = new javax.swing.JLabel();
        produto = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        tituloProduto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(null);

        painelTop.setBackground(new java.awt.Color(105, 85, 251));
        painelTop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelTop.setForeground(new java.awt.Color(204, 204, 204));
        painelTop.setLayout(null);

        tituloPage.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        tituloPage.setForeground(new java.awt.Color(255, 255, 255));
        tituloPage.setText("Seus Produtos");
        painelTop.add(tituloPage);
        tituloPage.setBounds(301, 26, 228, 40);

        add(painelTop);
        painelTop.setBounds(0, 0, 810, 100);

        produto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 85, 251)));
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        add(produto);
        produto.setBounds(20, 150, 230, 30);

        jPanel10.setBackground(new java.awt.Color(105, 85, 251));
        jPanel10.setMaximumSize(new java.awt.Dimension(4, 4));
        jPanel10.setMinimumSize(new java.awt.Dimension(270, 4));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel10);
        jPanel10.setBounds(250, 150, 10, 30);

        tituloProduto.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        tituloProduto.setForeground(new java.awt.Color(255, 255, 255));
        tituloProduto.setText("Digite o Codigo do Produto:");
        add(tituloProduto);
        tituloProduto.setBounds(20, 110, 310, 30);

        jTable2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 85, 251), 2, true));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2);
        jScrollPane2.setBounds(340, 110, 453, 403);
    }// </editor-fold>//GEN-END:initComponents

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel painelTop;
    private javax.swing.JTextField produto;
    private javax.swing.JLabel tituloPage;
    private javax.swing.JLabel tituloProduto;
    // End of variables declaration//GEN-END:variables
}
