/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import static java.lang.Thread.sleep;

/**
 *
 * @author 393144069
 */
public class telaLoding extends javax.swing.JFrame {

    /**
     * Creates new form telaLoding
     */
    public telaLoding() {
        initComponents();
        new Thread() {
            public void run() {
                for (int i = 0; i <= 101; i++) {
                    try {
                        sleep(53);
                        jProgressBar1.setValue(i);

                        if (jProgressBar1.getValue() <= 10) {
                            carregamento.setText("Carregando.");
                        } else if (jProgressBar1.getValue() <= 20) {
                            carregamento.setText("Carregando..");
                        } else if (jProgressBar1.getValue() <= 30) {
                            carregamento.setText("Carregando...");
                        } else if (jProgressBar1.getValue() <= 40) {
                            carregamento.setText("Carregando");
                        } else if (jProgressBar1.getValue() <= 50) {
                            carregamento.setText("Carregando.");
                        } else if (jProgressBar1.getValue() <= 60) {
                            carregamento.setText("Carregando..");
                        } else if (jProgressBar1.getValue() <= 70) {
                            carregamento.setText("Carregando...");
                        } else if (jProgressBar1.getValue() <= 80) {
                            carregamento.setText("Carregando");
                        } else if (jProgressBar1.getValue() <= 90) {
                            carregamento.setText("Carregando...");
                        } else {
                            carregamento.setText("Concluido");

                        }
                    } catch (InterruptedException ex) {
                    }
                }
                menuInicial tl = new menuInicial();
                tl.setVisible(true);
                dispose();
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carregamento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        carregamento.setBackground(new java.awt.Color(255, 255, 255));
        carregamento.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        carregamento.setForeground(new java.awt.Color(105, 85, 251));
        getContentPane().add(carregamento);
        carregamento.setBounds(340, 390, 210, 40);

        jLabel3.setBackground(new java.awt.Color(51, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(105, 85, 251));
        jLabel3.setText("2 IRMÃOS ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 60, 560, 90);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gif-loading.gif"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -10, 800, 600);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(170, 420, 410, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaLoding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel carregamento;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
