/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author lucas
 */
public class visualizarProdutos extends javax.swing.JFrame {

    /**
     * Creates new form visualizarProdutos
     */
    public visualizarProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelTop = new javax.swing.JPanel();
        tituloPage = new javax.swing.JLabel();
        produto = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        tituloProduto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        painelTop1 = new javax.swing.JPanel();
        tituloPage1 = new javax.swing.JLabel();
        tituloProduto1 = new javax.swing.JLabel();
        produto1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        painelTop.setBackground(new java.awt.Color(105, 85, 251));
        painelTop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelTop.setForeground(new java.awt.Color(204, 204, 204));
        painelTop.setLayout(null);

        tituloPage.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        tituloPage.setForeground(new java.awt.Color(255, 255, 255));
        tituloPage.setText("Seus Produtos");
        painelTop.add(tituloPage);
        tituloPage.setBounds(300, 10, 228, 40);

        jPanel1.add(painelTop);
        painelTop.setBounds(0, 0, 810, 70);

        produto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 85, 251)));
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        jPanel1.add(produto);
        produto.setBounds(40, 130, 230, 30);

        jPanel10.setBackground(new java.awt.Color(105, 85, 251));
        jPanel10.setMaximumSize(new java.awt.Dimension(4, 4));
        jPanel10.setMinimumSize(new java.awt.Dimension(270, 4));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10);
        jPanel10.setBounds(270, 130, 10, 30);

        tituloProduto.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        tituloProduto.setForeground(new java.awt.Color(255, 255, 255));
        tituloProduto.setText("Digite o Codigo do Produto:");
        jPanel1.add(tituloProduto);
        tituloProduto.setBounds(30, 90, 310, 30);

        jTable2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 85, 251), 2, true));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(390, 90, 410, 403);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        painelTop1.setBackground(new java.awt.Color(105, 85, 251));
        painelTop1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelTop1.setForeground(new java.awt.Color(204, 204, 204));
        painelTop1.setLayout(null);

        tituloPage1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        tituloPage1.setForeground(new java.awt.Color(255, 255, 255));
        tituloPage1.setText("Seus Produtos");
        painelTop1.add(tituloPage1);
        tituloPage1.setBounds(300, 10, 228, 40);

        getContentPane().add(painelTop1);
        painelTop1.setBounds(0, 0, 810, 70);

        tituloProduto1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        tituloProduto1.setForeground(new java.awt.Color(255, 255, 255));
        tituloProduto1.setText("Digite o Codigo do Produto:");
        getContentPane().add(tituloProduto1);
        tituloProduto1.setBounds(260, 80, 310, 30);

        produto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 85, 251)));
        produto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produto1ActionPerformed(evt);
            }
        });
        getContentPane().add(produto1);
        produto1.setBounds(290, 120, 230, 30);

        jPanel11.setBackground(new java.awt.Color(105, 85, 251));
        jPanel11.setMaximumSize(new java.awt.Dimension(4, 4));
        jPanel11.setMinimumSize(new java.awt.Dimension(270, 4));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11);
        jPanel11.setBounds(520, 120, 10, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bk.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 70, 800, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoActionPerformed

    private void produto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualizarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualizarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualizarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualizarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visualizarProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel painelTop;
    private javax.swing.JPanel painelTop1;
    private javax.swing.JTextField produto;
    private javax.swing.JTextField produto1;
    private javax.swing.JLabel tituloPage;
    private javax.swing.JLabel tituloPage1;
    private javax.swing.JLabel tituloProduto;
    private javax.swing.JLabel tituloProduto1;
    // End of variables declaration//GEN-END:variables
}
